# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: required
#dist: trusty
os:
  - linux
julia:
  - 0.6
notifications:
  email: false
addons:
      apt_packages:
        - gfortran
#before_install:
#- sudo apt-get -qq update
#- sudo apt-get install -y pdf2svg
#- sudo apt-get install -y texlive-latex-base
#- sudo apt-get install -y texlive-binaries
#- sudo apt-get install -y texlive-pictures
#- sudo apt-get install -y texlive-latex-extra
#- sudo apt-get install xzdec
#- sudo apt-get install luatex
#sudo apt-get update
install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install -c conda-forge matplotlib
#sudo apt-get install python-matplotlib  # for pyplot
after_success:
- echo $TRAVIS_JULIA_VERSION
- if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
- julia -e 'run(`lualatex -v`)'
- julia -e 'Pkg.clone(pwd())'
- julia -e 'Pkg.clone("https://github.com/JuliaMPC/VehicleModels.jl")'
- julia -e 'Pkg.clone("https://github.com/JuliaMPC/PrettyPlots.jl")'
- julia -e 'Pkg.clone("https://github.com/JuliaMPC/NLOptControl.jl")'
- julia -e 'Pkg.add("Documenter");'
- julia -e 'cd(Pkg.dir("MPCDocs"));ENV["DOCUMENTER_DEBUG"]=true; include(joinpath("docs", "make.jl"))'
